POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoiaWFtQGV4YW1wbGUuY29tIiwiaWF0IjoxNzUxNjI5OTcwLCJleHAiOjE3NTE2MzM1NzAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.dSfxSf0NupGMSvP46_8z1nXyYcjlmKFoMzBhYY622P4

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImlhdCI6MTc1MTYyOTk3MCwiZXhwIjoxNzUxNzE2MzcwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.MHCofC9TQhg_ZCnK1k90Vk-kbMsLvUaxMWxI2Y0cAcg"
}